name: Deploy to TimeWeb

on:
  push:
    branches: [ "main" ]  # Или другая ветка, которую хотите деплоить

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 
          "
            set -e
            cd ${{ secrets.PROJECT_DIR }}
            git fetch origin
            git reset --hard origin/main
            if [ -f venv/bin/activate ]; then
              source venv/bin/activate
              pip install -r requirements.txt
            fi
            sudo systemctl restart gunicorn
            sudo systemctl reload nginx
          "