name: Deploy to TimeWeb

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
            cd ${{ secrets.PROJECT_DIR }} &&
            git -c safe.directory=${{ secrets.PROJECT_DIR }} pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl daemon-reload &&
            sudo systemctl restart dashapp &&
            sudo systemctl restart nginx
          